#!/bin/sh -ex

ZWACONF=.zwaconf

TARGET=

if [ -f $ZWACONF ]; then
  . ./$ZWACONF
fi

if [ -z "$TARGET" ]; then
  TARGET=$PWD/out
fi

get_version(){
      head -1 debian/changelog | sed -e 's/.*(\([^)]*\)).*/\1/'
}

sed_file() {

    while [ -n "$1" ]; do
        in=$1.in
        out=$1

        sed \
            -e "s,@TARGET@,${TARGET},g" \
            -e "s/@VERSION@/${VERSION}/g" \
            $in > $out
        shift
    done
}

cmd=$1

shift
case "$cmd" in
  get-version)
    get_version
    ;;
  prepare-dist)
    VERSION=`get_version`
    ;;
  dist-exclude-list|build-exclude-list)
    echo "out obj *.aqt *.ncb *.suo *.vcproj.*.user"
    ;;
  bootstrap)
    ;;
  configure)
    OPTIONS=`getopt -l help,prefix: 'p:' $*`
    if [ $? -ne 0 ]; then
      echo "$0: unknown flags..."
      exit 1
    fi

    eval set -- "$OPTIONS"
    while true ; do
      _arg=$1

      if [ -z "$_arg" ]; then
        break
      fi
      case $1 in
        --prefix|-p)
          shift
          TARGET=`cygpath -u "$1"`
          ;;
      esac
      shift
    done
    cat << EOF > $ZWACONF
TARGET="$TARGET"
EOF
    ;;
  make)
      root=`pwd`
      if [ -z "$1" ];then
          mkdir -p wpcap/lib
          cd packetNtx/Dll/Project
          $MAKE LEX=flex DDKFLAGS="-I /usr/$build/sys-root/mingw/include/ddk"
          cd ../../..
          cd wpcap/PRJ
          $MAKE LEX=flex DDKFLAGS="-I /usr/$build/sys-root/mingw/include/ddk"
      else
          case "$1" in
            install)
                packetpath=$root/packetNtx/Dll/Project
                pcappath=$root/wpcap/libpcap
                mkdir -p $TARGET/bin $TARGET/lib $TARGET/include/pcap/
                cp -v $packetpath/packet.dll $root/wpcap/PRJ/wpcap.dll $TARGET/bin
                for i in $packetpath/libpacket.a $root/wpcap/lib/libwpcap.a; do
                  b=`basename $i .a`;
                  impname=${b}.dll.a
                  cp -v "$i" "$TARGET/lib/$impname"
                done
                cp -v -a \
                  $root/Common/Packet32.h \
                  $root/wpcap/Win32-Extensions/Win32-Extensions.h \
                  $pcappath/Win32/Include/bittypes.h \
                  $pcappath/Win32/Include/ip6_misc.h \
                  $pcappath/remote-ext.h \
                  $pcappath/pcap-bpf.h \
                  $pcappath/pcap-namedb.h \
                  $pcappath/pcap-stdinc.h \
                  $pcappath/pcap.h \
                  $pcappath/pcap \
                  $TARGET/include/pcap
                find $TARGET/lib $TARGET/include -type f | xargs -r chmod -x
            ;;
            clean)
              cd packetNtx/Dll/Project
              $MAKE LEX=flex DDKFLAGS="-I /usr/$build/sys-root/mingw/include/ddk"
              cd $root/wpcap/PRJ
              $MAKE LEX=flex DDKFLAGS="-I /usr/$build/sys-root/mingw/include/ddk"
              cd $root
            ;;
            *) echo unknown make option: $1 ;;
          esac
      fi
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0

# vim: ts=2 sw=2 expandtab
